apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arcanum-cr
rules:
- apiGroups:
  - njha.dev
  resources:
  - syncedsecrets
  - syncedsecrets/status
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - create
  - patch
