apiVersion: v1
kind: Service
metadata:
  labels:
    app: arcanum
  name: arcanum
  namespace: arcanum
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: arcanum
