apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arcanum
  name: arcanum
  namespace: arcanum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcanum
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: arcanum
    spec:
      containers:
      - env:
        - name: ARCANUM_VLT_HOST
          valueFrom:
            secretKeyRef:
              key: ARCANUM_VLT_HOST
              name: arcanum-secret
        - name: ARCANUM_VLT_PATH
          valueFrom:
            secretKeyRef:
              key: ARCANUM_VLT_PATH
              name: arcanum-secret
        - name: ARCANUM_VLT_TOKEN
          valueFrom:
            secretKeyRef:
              key: ARCANUM_VLT_TOKEN
              name: arcanum-secret
        - name: ARCANUM_ENC_KEY
          valueFrom:
            secretKeyRef:
              key: ARCANUM_ENC_KEY
              name: arcanum-secret
        image: ghcr.io/nikhiljha/arcanum:v0.1.0@sha256:ff0f313bf03454fbd372ad9318c4fa6dd7b9d1bcf7921180e24622f30389e653
        imagePullPolicy: IfNotPresent
        name: arcanum
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
      serviceAccountName: arcanum-sa
