vault:
  global:
    enabled: true
    tlsDisable: false

  server:
    # TODO: Fix this.
    readinessProbe:
      enabled: false
    livenessProbe:
      enabled: false
      initialDelaySeconds: 60

    # https://www.vaultproject.io/docs/audit/index.html
    auditStorage:
      enabled: true
      storageClass: rook-ceph-block

    dataStorage:
      storageClass: rook-ceph-block

    image:
      tag: "1.6.0"

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/ingress.class: contour
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: vault.ocf.berkeley.edu
        paths: []
      tls:
      - hosts:
        - vault.ocf.berkeley.edu
        secretName: vault-ingress-tls

    # in favor of HA, disable standalone
    standalone:
      enabled: false

    ha:
      enabled: true
      replicas: 3
      # the other option is consul
      raft:
        enabled: true
        setNodeId: true

  # enable UI service
  ui:
    enabled: true



# This is a separate helm chart.
vault-secrets-operator:
  vault:
    authMethod: kubernetes
  # TODO: Enable prometheus operator.
