apiVersion: njha.dev/v1
kind: SyncedSecret
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: speaker
    app.kubernetes.io/instance: ocf-metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    helm.sh/chart: metallb-2.3.7
  name: ocf-metallb-memberlist
spec:
  data:
    secretkey: DjDFiBdt2L5ui/tdcJ2II0Jy/a+Cy8l1fh15SVAm4wyePvPsqRgwNnR3DtLnbTfXLcxParlcH8u8OH650YXb/TDYAEZpBpmcte1c4fjQlnSOAlNBrPKprcbXOAUkukU3Ss3VyGmz4Z565J80sw3Dk+mrgEFqGCN85+4qK3LUFmU+8E5Tx9EuLiMbX9I23eAj/UcwCVhMZL5Tq8Ce6gM+JT3rTtzvplh8mB57MGT9tPqZlMO6hhbUQ90iL8EqMnSCwk+tjg/CmbkY55C3VXFCvzn55jOtx+iNWNjXIbXPni0nESz1axzw5BqGfkaZzOoLEyGqzPtv8TEqtpJ/dhI+n1+e50vb9LlqUi9fuuxQHmMRZxnf2WGAPSYRAG6xI/s+ljrqFLhZzjWb+GNWhSy+QB/8FNS+MD47jh2zfg==
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
