apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: hubble-ui
  name: hubble-ui
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hubble-ui
  template:
    metadata:
      annotations: null
      labels:
        k8s-app: hubble-ui
    spec:
      containers:
      - image: quay.io/cilium/hubble-ui:v0.8.3@sha256:018ed122968de658d8874e2982fa6b3a8ae64b43d2356c05f977004176a89310
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 8080
          name: http
      - env:
        - name: EVENTS_SERVER_PORT
          value: '8090'
        - name: FLOWS_API_ADDR
          value: hubble-relay:80
        image: quay.io/cilium/hubble-ui-backend:v0.8.3@sha256:13a16ed3ae9749682c817d3b834b2f2de901da6fb41de7753d7dce16650982b3
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 8090
          name: grpc
        volumeMounts: null
      - args:
        - -c
        - /etc/envoy.yaml
        - -l
        - info
        command:
        - envoy
        image: docker.io/envoyproxy/envoy:v1.18.4@sha256:e5c2bb2870d0e59ce917a5100311813b4ede96ce4eb0c6bfa879e3fbe3e83935
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 8081
          name: http
        volumeMounts:
        - mountPath: /etc/envoy.yaml
          name: hubble-ui-envoy-yaml
          subPath: envoy.yaml
      priorityClassName: null
      securityContext:
        runAsUser: 1001
      serviceAccount: hubble-ui
      serviceAccountName: hubble-ui
      volumes:
      - configMap:
          name: hubble-ui-envoy
        name: hubble-ui-envoy-yaml
