apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/instance: ocf-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.5
    helm.sh/chart: grafana-6.9.1
  name: ocf-prometheus-grafana
  namespace: prometheus
spec:
  data:
    admin-password: WlTpHgC21WxfNUaqnIVEdHJAB9nPiG80Erz9yugOaOmNrB0XCowL4df5TsU+i+4UA5RR4xWm+0lWfDuwz6uZvCKt2XhPMA6Z1Q==
    admin-user: fFzhcykILTWq6MW/LK6jHtgxhiwspAiM6fxJIqnrzM1ZGQW4c7+t+AFnrHr3y/kMBY9wSEaK1PF8gCmmPEtD6JM=
    ldap-toml: J3VLRv7t/cbWw1mo6faPf4xKpBJP7ZV7QMr+SxMTAbCTLZ74dSRlmhCvxLWluR9AOeXLbcyLdtRmxzR1
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
