apiVersion: v1
data:
  _example: "################################\n#                              #\n\
    #    EXAMPLE CONFIGURATION     #\n#                              #\n################################\n\
    \n# This block is not actually functional configuration,\n# but serves to illustrate\
    \ the available configuration\n# options and document them in a way that is accessible\n\
    # to users that `kubectl edit` this config map.\n#\n# These sample configuration\
    \ options may be copied out of\n# this example block and unindented to be in the\
    \ data block\n# to actually change the configuration.\n\n# Common configuration\
    \ for all Knative codebase\nzap-logger-config: |\n  {\n    \"level\": \"info\"\
    ,\n    \"development\": false,\n    \"outputPaths\": [\"stdout\"],\n    \"errorOutputPaths\"\
    : [\"stderr\"],\n    \"encoding\": \"json\",\n    \"encoderConfig\": {\n     \
    \ \"timeKey\": \"ts\",\n      \"levelKey\": \"level\",\n      \"nameKey\": \"\
    logger\",\n      \"callerKey\": \"caller\",\n      \"messageKey\": \"msg\",\n\
    \      \"stacktraceKey\": \"stacktrace\",\n      \"lineEnding\": \"\",\n     \
    \ \"levelEncoder\": \"\",\n      \"timeEncoder\": \"iso8601\",\n      \"durationEncoder\"\
    : \"\",\n      \"callerEncoder\": \"\"\n    }\n  }\n"
  loglevel.controller: info
  loglevel.webhook: info
  zap-logger-config: "{\n  \"level\": \"debug\",\n  \"development\": true,\n  \"sampling\"\
    : {\n    \"initial\": 100,\n    \"thereafter\": 100\n  },\n  \"outputPaths\":\
    \ [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\": \"json\"\
    ,\n  \"encoderConfig\": {\n    \"timeKey\": \"\",\n    \"levelKey\": \"level\"\
    ,\n    \"nameKey\": \"logger\",\n    \"callerKey\": \"caller\",\n    \"messageKey\"\
    : \"msg\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\": \"\",\n\
    \    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"\",\n    \"durationEncoder\"\
    : \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"
kind: ConfigMap
metadata:
  labels:
    operator.tekton.dev/release: devel
  name: config-logging
  namespace: tekton-operator
