apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: v0.52.0
    version: v0.52.0
  name: tekton-operator-webhook
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator-webhook
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator-webhook
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: WEBHOOK_SERVICE_NAME
          value: tekton-operator-webhook
        - name: WEBHOOK_SECRET_NAME
          value: tekton-operator-webhook-certs
        - name: METRICS_DOMAIN
          value: tekton.dev/operator
        image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/webhook:v0.52.0@sha256:af226b769cb133d174de51e4e6eefd8666a0f713a7cc5a6efb74864ee7e974ab
        name: tekton-operator-webhook
        ports:
        - containerPort: 8443
          name: https-webhook
      serviceAccountName: tekton-operator
