apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: v0.52.0
    version: v0.52.0
  name: tekton-operator
  namespace: tekton-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: tekton-operator
        - name: IMAGE_PIPELINES_PROXY
          value: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/proxy-webhook:v0.52.0@sha256:cb4d495f726b1b4dd80c0b6e6711897e818a6d6f1721d423d60f85d34ffa3777
        - name: IMAGE_JOB_PRUNER_TKN
          value: gcr.io/tekton-releases/dogfooding/tkn@sha256:025de221fb059ca24a3b2d988889ea34bce48dc76c0cf0d6b4499edb8c21325f
        - name: METRICS_DOMAIN
          value: tekton.dev/operator
        - name: VERSION
          value: devel
        - name: CONFIG_OBSERVABILITY_NAME
          value: tekton-config-observability
        - name: AUTOINSTALL_COMPONENTS
          valueFrom:
            configMapKeyRef:
              key: AUTOINSTALL_COMPONENTS
              name: tekton-config-defaults
        - name: DEFAULT_TARGET_NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_TARGET_NAMESPACE
              name: tekton-config-defaults
        image: gcr.io/tekton-releases/github.com/tektoncd/operator/cmd/kubernetes/operator:v0.52.0@sha256:14d1cb3bec0f7ace61437c2dda99d9891ba714b56bed071f6aa2959a26955469
        imagePullPolicy: Always
        name: tekton-operator
      serviceAccountName: tekton-operator
