apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-core
spec:
  data:
    secret: pUWqjw/0ddcjYgJD7dNyxuUcvdRDEb3tqQ6DU6IItFItV/X79MX9qfcrAbrUvGPT0Ndxf8bGfcANt3kEJsWzJ58PlroZlu+6YQy4tg==
    secretKey: BeWffYvNQpeMmwXe7t+Qo8M0CKSpuOjhm/k6O6dCfIg5t5Lm45p4vJHH91OspHuJ46bMy1dvrJqd4dPrdDd67hYVRaHCEdXrUxuUeg==
    tls.crt: ''
    tls.key: ''
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
