apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/component: jobservice
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-jobservice
spec:
  data:
    secret: 4SENQ9gt6Wz4YALLqCa2ZRs04godySe5S1sBXEzja98sXhA1ke4Pg7cXTuFV/mNMSHDMmstTXCSqkxRNsoMyDElcxMBgMIQ4b7L/EQ==
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
