apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/component: chartmuseum
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-chartmuseum-secret
spec:
  data:
    CACHE_REDIS_PASSWORD: kCHMx/uZZYTjqlvYEE4I3iHEY3m3CqdkIchoJ93aL7k2N4U2DyW7UyTqNRquCmzvA7GggeJGcFhp2UBW
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
