apiVersion: njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: ocf-harbor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: harbor
    helm.sh/chart: harbor-10.0.4
  name: ocf-harbor-core
spec:
  data:
    secret: dBUXo1qDgaTRQ5XhtRyZjLYuO/bBqxdxRMGj8G5FAGAAX0U/EsGOozwO8Ja/oO12qNdkND2YBiwTQ5cgWOLkTG4ezEsbyNhFiytd3Q==
    secretKey: 0QThjevl5xgLyyFM5dLwTOE8/npomQMxa9yzpMIMC3GPq+6tiALqM3N3bKysLMXJwgk3CLfAyJmDUk65ADr1s36N2nDKbpG0Y3Hv3Q==
    tls.crt: ''
    tls.key: ''
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
