apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mycelium-operator
  name: mycelium-operator
  namespace: mycelium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycelium-operator
  template:
    metadata:
      annotations:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: mycelium-operator
    spec:
      containers:
      - env:
        - name: MYCELIUM_FW_TOKEN
          valueFrom:
            secretKeyRef:
              key: forwarding_token
              name: mycelium-operator
        - name: MYCELIUM_ENDPOINT
          value: mycelium-operator.mycelium.svc.cluster.local:8080
        image: harbor.ocf.berkeley.edu/mycelium/operator:0.2.0
        name: operator
        ports:
        - containerPort: 8080
          name: api
        readinessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
      serviceAccountName: mycelium-operator
