apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycelium-operator
rules:
- apiGroups:
  - mycelium.njha.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - events
  verbs:
  - '*'
