apiVersion: v2
name: traefik
version: 1.0.0
dependencies:
  - name: traefik
    # https://github.com/traefik/traefik-helm-chart/issues/309
    version: 9.10.0
    repository: https://helm.traefik.io/traefik