cilium:
  kubeProxyReplacement: "strict"
  k8sServiceHost: "127.0.0.1"
  k8sServicePort: "6443"
  nativeRoutingCIDR: 10.0.0.0/8
  containerRuntime:
    integration: "containerd"
    socketPath: "/run/containerd/containerd.sock"
