apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              metadata:
                generateName: ci-oci-build-
                namespace: argo
              spec:
                entrypoint: build
                serviceAccountName: argo
                volumes:
                  - name: workflow-account
                    secret:
                      secretName: workflow-account
                templates:
                  - name: build
                    inputs:
                      artifacts:
                        - name: source
                          path: /src
                          git:
                            repo: "https://github.com/ocf/templates"
                            revision: "master"
                    container:
                      image: gcr.io/kaniko-project/executor
                      env:
                      - name: AWS_S3_USE_ARN_REGION
                        value: "false"
                      args:
                        - "--context=/src"
                        - "--destination=harbor.ocf.berkeley.edu/library/templates:master"
                      volumeMounts:
                        - name: workflow-account
                          mountPath: /kaniko/.docker/
                          readOnly: true
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.arguments.parameters.0.value