apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    license.k8s.elastic.co/scope: operator
  name: eck-license
spec:
  data:
    license: YO7tYAPw7kQKE/I0ZK+BXzKdKzBDIFQDbnBL/yoF+sqzQ5HG+4kGDVzSOXtrsrRbaPLBeitisvmR7b/DgBFVkz6jYh50IZxH3G12VlmgrSmTpXZyVFQhQa+J0TqaZ3LI9LVihnJBfQ==
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
