apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  nodeSets:
  - config:
      node.store.allow_mmap: false
    count: 3
    name: default
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            capabilities:
              add:
              - SYS_CHROOT
  version: 7.15.1
