apiVersion: arcanum.njha.dev/v1
kind: SyncedSecret
metadata:
  labels:
    app.kubernetes.io/instance: ocf-elastic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: eck-operator-1.8.0
  name: elastic-operator-webhook-cert
  namespace: elastic
spec:
  data: {}
  pub_key: 08TiLEIqvq2yDWSx1yGNwI5ICtld+ZyMzuvxqXxkA8M=
