apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  nodeSets:
  - config:
      node.store.allow_mmap: false
    count: 1
    name: default
  version: 7.15.1
