apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: ocf
spec:
  config:
    ent_search.external_url: https://finder.ocf.berkeley.edu
    kibana.external_url: https://kibana.ocf.berkeley.edu
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.15.1
